# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/hodovani/pre-commit-swift
    rev: 0551a937b9f98a839fd98d2c3e6ce0b6c0a1e093
    hooks:
      - id: swift-format
