name: "Generate Documentation"

on:
    push:
        branches:
            - "main"

jobs:
    "GenerateDocumentation":
        runs-on: "macos-latest"
        steps:
            - uses: "actions/checkout@v2"
            - name: "Clone swift-docc and swift-docc-render"
              run: "gh repo clone apple/swift-docc apple/swift-docc-render"
            - name: "Build swift-docc-render"
              run: "cd swift-docc-render/ && npm install && npm run build && cd .."
            - name: "Build swift-docc & TOMLKit"
              run: |
                  swift build -c release --package-path swift-docc
                  swift build --target TOMLKit -Xswiftc -emit-symbol-graph -Xswiftc -emit-symbol-graph-dir -Xswiftc .build
            - name: "Build documentation"
              run: |
                  export DOCC_HTML_DIR=swift-docc-render/dist
                  ./swift-docc/.build/release/docc convert \
                  Sources/TOMLKit/TOMLKit.docc \
                  --fallback-display-name TOMLKit \
                  --fallback-bundle-identifier com.LebJe.TOMKit \
                  --fallback-bundle-version 1 \
                  --additional-symbol-graph-dir .build \
                  --output-dir docs
                  ./swift-docc/.build/release/docc process-archive transform-for-static-hosting docs --hosting-base-path /TOMLKit
            - name: "Deploy to GitHub Pages"
              uses: "peaceiris/actions-gh-pages@v3"
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: "docs"
